#ifndef __settings_h__
#define __settings_h__

#include "group.h"

typedef struct
{
	char*    manifest_repo;
	char*    manifest_name;
	char*    manifest_path; /* Autogenerated. */
	bool     mirror;
	group_t* group;
	unsigned group_count;
	char*    group_string; /* Do not modify. */
} settings_t;

extern settings_t* settings_create(bool mirror);
extern void        settings_delete(settings_t* settings);

extern bool settings_manifest_repo_set(
	settings_t* settings, const char* repo);
extern bool settings_manifest_name_set(
	settings_t* settings, const char* name);

extern const char* settings_manifest_path_get(
	settings_t* settings);

extern settings_t* settings_read(const char* path);
extern bool        settings_write(settings_t* settings, const char* path);

#endif
